### ISSUE TITLE
New device type with command dt_scaling

### ISSUE THREAD

**Issue by tikismoke** [vdomos/domogik-plugin-vdevice#3]
Could you had a new device that will contains a command of typr DT_scaling.

I could change the sensor but not th command if i try with a virtual number.

Goal is to debug domodroid problems with this type of device.

**Comment by tikismoke** [comment]
Seems I didn't see device percent ;)

Crap it is no more available.

**Comment by vdomos** [comment]
sorry, I was not available this last week

I also saw that the command kept the DT_Number type.
I don't have problem with that, you can change sensor even if sensors and commands  are in different types
it's for Domodroid ?

**Comment by tikismoke** [comment]
No problem ;)

Yes to test the domodroid widget range I need a DT_scaling command.

To validate the use I change the dttype in domodroid dB directly, it was easy for me but it certainly not the right way. Maybe it is a request to do in Domogik to allow command edit don't really know.
