### ISSUE TITLE
Add dt_color

### ISSUE THREAD

**Issue by tikismoke** [vdomos/domogik-plugin-vdevice#4]
Hi Domos to help me debug domodroid color widget, i'll need a dt_color sensor and command.
Do you think it's easy to add for you as a new vdevice type?

**Comment by vdomos** [comment]
Hello Tiki,
there is many type of DT_Color:
"DT_ColorRGB"
"DT_ColorCMYK"
"DT_ColorRGBHexa"
"DT_ColorCII"

which do you need ?

**Comment by tikismoke** [comment]
Need to see Fritz to be sure what his rgb light use.

I'm pretty sure rgb or hexa are enough for now.

**Comment by tikismoke** [comment]
In generic for arduino it use DT_ColorRGBHexa.

This should be the right but rgb only could also be useful for other stuff in future.

Focus in those in plugin and I'll do same in domodroid.

**Comment by vdomos** [comment]
it'done.
I had DT_ColorRGB and DT_ColorRGBHexa device.
Tell me if it's ok for you.

**Comment by tikismoke** [comment]
Ok thank's it works for hexa.

Need to work on the other one as parent dt_type is list and make problems with it in doodroid.
